# fly.toml app configuration file generated for codestorm-cryptotrader on 2025-07-02T23:24:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'codestorm-cryptotrader'
primary_region = 'otp'

[build]
  dockerfile = '.\CodeStorm.CryptoTrader.BotService\Docker-fly-io-file'

[[processes]]
  type = "worker"
  cmd = ["dotnet", "CodeStorm.CryptoTrader.BotService.dll"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[scale]
  count = 1
